[project]
authors = ["Mirco <61457049+mircmo@users.noreply.github.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "advent-of-code-2024"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
numpy = ">=1.26.4,<2"
